services:
  contactmanager:
    image: contactmanager:dev
    build:
      context: .
      dockerfile: ContactManager/Dockerfile
    container_name: contactmanager_api
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=ContactManagerDb;User Id=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True;"
    volumes:
      - dpkeys:/app/keys
    ports:
      - "8080:8080"
    networks:
      - appnet
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: contactmanager_mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P $${SA_PASSWORD} -Q \"SELECT 1\" -C || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - appnet
    restart: unless-stopped
    ports:
      - "1433:1433"

networks:
  appnet:

volumes:
  mssql_data:
  dpkeys:
